DROP DATABASE ADVERTISING;
CREATE DATABASE ADVERTISING;
USE ADVERTISING;

CREATE TABLE USER (
	UID INT NOT NULL AUTO_INCREMENT,
	EMAIL VARCHAR(40) UNIQUE,
    PASSWORD VARCHAR(40) NOT NULL,
    HOMETOWN VARCHAR(40),
    FNAME VARCHAR(40) NOT NULL,
    LNAME VARCHAR(40) NOT NULL,
    PRIMARY KEY (UID)
);

CREATE TABLE BUSINESS (
	EMAIL VARCHAR(40) NOT NULL,
	HOUSENUM VARCHAR(40) NOT NULL,
	STREET VARCHAR(40) NOT NULL,
	CITY VARCHAR(40) NOT NULL,
	STATE VARCHAR(40) NOT NULL,
	MESSAGE VARCHAR(100) NOT NULL
);